name: UW DevBlog
markdown: redcarpet
pygments: false
permalink: /blog/:title
exclude: ['_assets', '_submodules', 'node_modules', 'Gruntfile.js', 'package.json', 'uw_bootstrap']
tag_page_layout: tag_page
tag_page_dir: tag 
category_dir: category
